CREATE TABLE settings_data (
  id INTEGER NOT NULL PRIMARY KEY,
  application VARCHAR UNIQUE NOT NULL,
  settings_json TEXT NOT NULL,
  created_at TIMESTAMP UNIQUE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE notification_data 
ADD COLUMN archived BOOLEAN NOT NULL DEFAULT 0
