

CREATE TABLE notification_data (
  id INTEGER NOT NULL PRIMARY KEY,
  sender VARCHAR NOT NULL,
  title VARCHAR NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP UNIQUE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archived BOOLEAN NOT NULL DEFAULT 0,
  unread BOOLEAN NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX application_name ON settings_data(application);

CREATE TABLE settings_data (
  id INTEGER NOT NULL PRIMARY KEY,
  application VARCHAR UNIQUE NOT NULL,
  settings_json TEXT NOT NULL,
  created_at TIMESTAMP UNIQUE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
 
SELECT diesel_manage_updated_at('notification_data');
